spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/art_school
spring.datasource.username=postgres
spring.datasource.password=30057063Aa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true